## Basic Configuration

baseURL = "https://westley-winks.github.io/hugo-starting-point/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

## contentdir = "content"
## layoutdir = "layouts"
## publishdir = "public"

author = "Name"
title = "Name"

## Hugo Built-in Features
## googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Name"
intro = "Title"
description = "Description"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Description"
keywords = "hugo, portfolio"

## Social Accounts
[params.social]
github = "<username>"
instagram = "<username>"
linkedin = "<username>"
youtube = "<channelid>"
email = "you@example.com"
## xing = "<username>"
## twitter = "<username>"
## facebook = "<username>"
## google = "<username>"
## googlescholar = "<account_id>"
## stackoverflow = "<username>"
## lastfm = "<username>"
## goodreads = "<username>"
## gitlab = "<username>"
## bitbucket = "<username>"
## fivehundredpx = "<username>"
## flickr = "<username>"
## foursquare = "<username>"
## hackernews = "<username>"
## kickstarter = "<username>"
## patreon = "<username>"
## pintrest = "<username>"
## steam = "<username>"
## reddit = "<username>"
## snapchat = "<username>"
## keybase = "<username>"
## twitch = "<username>"
## soundcloud = "<username>"
## tumblr = "<username>"
## strava = "<username>"
## skype = "<username>"
## telegram = "<username>"
## whatsapp = "<username>"
## pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "© 2022. Erlich Bachman."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true

## Main Menu
## [[menu.main]]
##     name = "about"
##     identifier = "about"
##     weight = 100
##     url = "/about/"